function A = Amatrix(IG,d,m,phi,theta)
%AMATRIX
%    A = AMATRIX(IG,D,M,PHI,THETA)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    07-May-2023 23:30:26

t2 = phi+theta;
t3 = sin(t2);
t4 = cos(t2);
A = reshape([-m,0.0,-d.*m.*sin(theta),-t3,0.0,-m,d.*m.*cos(theta),t4,0.0,0.0,IG,-d.*cos(phi),-t3,t4,0.0,0.0],[4, 4]);
