function b = bvector(T,d,g,m,omega,phi,phidot,theta,vGx,vGy)
%BVECTOR
%    B = BVECTOR(T,D,G,M,OMEGA,PHI,PHIDOT,THETA,VGX,VGY)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    07-May-2023 23:30:26

t2 = cos(theta);
t3 = phi+theta;
t4 = cos(t3);
t5 = sin(t3);
b = [-T.*t2;g.*m-T.*sin(theta);d.*g.*m.*t2;omega.*t4.*vGx+omega.*t5.*vGy+phidot.*t4.*vGx+phidot.*t5.*vGy-d.*omega.*phidot.*sin(phi)];
